#!/bin/bash

###############################################################
#          jupyter/jupyterlab extensions/kernels              #
###############################################################

# Building everything up
echo "Building everything up (jupyter lab build)"
jupyter lab build 

###############################################################
#             moving to a local installation folder           #
###############################################################

mkdir ~/resources/local
cd    ~/resources/local

###############################################################
#             cassandra installation commands                   #
###############################################################

export CASSANDRA_VERSION=3.11.11
echo "export CASSANDRA_VERSION=${CASSANDRA_VERSION}" >> ~/.bashrc
echo "export CASSANDRA_VERSION=${CASSANDRA_VERSION}" >> ~/.profile

export CASSANDRA_HOME=$(pwd)/apache-cassandra-${CASSANDRA_VERSION}
echo "export CASSANDRA_HOME=${CASSANDRA_HOME}"       >> ~/.bashrc
echo "export CASSANDRA_HOME=${CASSANDRA_HOME}"       >> ~/.profile

wget -q https://archive.apache.org/dist/cassandra/${CASSANDRA_VERSION}/apache-cassandra-${CASSANDRA_VERSION}-bin.tar.gz

tar xzf apache-cassandra-${CASSANDRA_VERSION}-bin.tar.gz
rm      apache-cassandra-${CASSANDRA_VERSION}-bin.tar.gz

# adding bin and sbin to $path
echo "export PATH=\$PATH:\$CASSANDRA_HOME/bin"  >> ~/.bashrc
echo "export PATH=\$PATH:\$CASSANDRA_HOME/bin"  >> ~/.profile

###############################################################
#             vscode server installation                      #
###############################################################

cd    ~/resources/local

export CODE_SERVER_VERSION=3.3.0
echo "export CODE_SERVER_VERSION=${CODE_SERVER_VERSION}" >> ~/.bashrc
echo "export CODE_SERVER_VERSION=${CODE_SERVER_VERSION}" >> ~/.profile

export CODE_SERVER_HOME=$(pwd)/code-server-${CODE_SERVER_VERSION}
echo "export CODE_SERVER_HOME=${CODE_SERVER_HOME}"       >> ~/.bashrc
echo "export CODE_SERVER_HOME=${CODE_SERVER_HOME}"       >> ~/.profile

# Download and install VSCode server
# wget -q -O code-server.tar.gz https://github.com/cdr/code-server/releases/download/$CODE_SERVER_VERSION/code-server-$CODE_SERVER_VERSION-linux-x86_64.tar.gz                            
wget -q -O code-server.tar.gz https://github.com/cdr/code-server/releases/download/v$CODE_SERVER_VERSION/code-server-$CODE_SERVER_VERSION-linux-amd64.tar.gz                            
tar xzf code-server.tar.gz
# mv code-server-${CODE_SERVER_VERSION}-linux-x86_64 code-server-$CODE_SERVER_VERSION
mv code-server-$CODE_SERVER_VERSION-linux-amd64 code-server-$CODE_SERVER_VERSION

rm -rf code-server.tar.gz

# adding bin/ to $path
echo "export PATH=\$PATH:\$CODE_SERVER_HOME/bin"   >> ~/.bashrc
echo "export PATH=\$PATH:\$CODE_SERVER_HOME/bin"   >> ~/.profile

source ~/.bashrc

