#!/bin/bash

mkdir logs


chmod +x ~/binder/start.cassandra 
chmod +x ~/binder/start.vscode 

# starting mongodb
~/binder/start.cassandra   &

# starting adminmongo in parallel
~/binder/start.vscode   &


cd ~
echo " " >> .gitignore
echo "resources/local/" >> .gitignore
echo ".local/" >> .gitignore
echo "local-home/" >> .gitignore


# DO NOT REMOVE(!) 
# Here is why: https://mybinder.readthedocs.io/en/latest/config_files.html#start-run-code-before-the-user-sessions-starts
exec "$@"
